### ISSUE TITLE
POC Roadmap

### ISSUE THREAD

**Issue by chrisparnin** [ottomatica/docable-notebooks#2]
* [x] do a tiny bit of clean-up: change format to json5, clean up css rules, look-n-feel.
* [x] integrate m2html inside main notebook server...
* [x] work on basic bridge for execution based on "data-attributes" in `docable`
* [x] work on executed, look and feel... how is output rendered and displayed.
* [ ] deal with "serialization" ... how are things saved?
